defaults               :
 -
  scope                :
    path               : "" # an empty string here means all files in the project
  values               :
    developer          : "George Freeney-Jones"
      company          : "Gaboogled"
      desc             : "Creative Technologist | \"Inspired by Skittles\""
      title            : "Environment : local"
      copyright        : "2019"
      env              : "local"
      keen             : "default"
      framework        : "2"
      layout           : "mdc-layout-grid--root"

# What do it look like?
      skin             : "./css/gaboogled.css"
      skin_pref        : "default"
      gtag             : "xxxxxxxx"
      small-logo       : "./imgs/gaboogle-aside-logo.png"
      github           : "gaboogled"
      gitpage          : "https://github.com/gaboogled"
      pipefy           : "https://app.pipefy.com/organizations/240226"

# Where things are
source                 : .
destination            : ./_site
collections_dir        : _collections
plugins_dir            : _plugins
layouts_dir            : _layouts
data_dir               : _data
includes_dir           : _includes
sass_dir               : _sass
collections:
  posts:
    output             : true

# Handling Reading
safe                   : false
include                : [".htaccess"]
exclude                : [".DS_Store", "gulpfile.js", "node_modules", "package.json", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files             : [".git", ".svn"]
encoding               : "utf-8"
markdown_ext           : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter    : false

# Filtering Content
show_drafts            : null
limit_posts            : 0
future                 : false
unpublished            : false

# Plugins & Gems
whitelist              : []
plugins                : ["jekyll-autoprefixer"]
gems                   : ["jekyll-babel"]

# Conversion
markdown               : kramdown
highlighter            : rouge
lsi                    : false
excerpt_separator      : "\n\n"
incremental            : false

# Serving
detach                 : false
port                   : 4000
host                   : 127.0.0.1
baseurl                : "" # does not include hostname
show_dir_listing       : false

# Outputting
permalink              : date
paginate_path          : /page:num
timezone               : null

quiet                  : false
verbose                : false
defaults               : []

liquid:
  error_mode           : warn
  strict_filters       : false
  strict_variables     : false
jekyll-bliss           :
  build-folder         : _build
  debug                : false
  quiet                : false
  delete-build-folder  : false
  livereload           : false

# Markdown Processors
rdiscount:
  extensions           : []

redcarpet:
  extensions           : []

kramdown:
  auto_ids             : true
  entity_output        : as_char
  toc_levels           : 1..6
  smart_quotes         : lsquo,rsquo,ldquo,rdquo
  input                : GFM
  hard_wrap            : false
  footnote_nr          : 1
  show_warnings        : false
